# ndarray
## 1、ndarray的特性
### 多维性

In [1]:
import numpy as np

In [3]:
arr = np.array(5) #创建0维的数组
print(arr)
print('arr的维度：',arr.ndim) # number of dimension

5
arr的维度： 0


In [2]:
arr = np.array([1])  #创建1维的数组
print(arr)
print('arr的维度：', arr.ndim)  # number of dimension

[1]
arr的维度： 1


In [3]:
arr = np.array([[1,2],[3,4]])  #创建2维的数组
print(arr)
print('arr的维度：', arr.ndim)  # number of dimension

[[1 2]
 [3 4]]
arr的维度： 2


### 同质性

## 2、ndarray的属性

In [14]:
arr = np.array(1)
print(arr)
print("数组的形状：",arr.shape)#按ctrl+k提交
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的类型：",arr.dtype)

1
数组的形状： ()
数组的维度 0
元素的个数 1
元素的类型： int64


In [15]:
arr = np.array([1,2.5])
print(arr)
print("数组的形状：",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的类型：",arr.dtype)

[1.  2.5]
数组的形状： (2,)
数组的维度 1
元素的个数 2
元素的类型： float64


In [16]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr)
print("数组的形状：",arr.shape)#两行两列
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的类型：",arr.dtype)
print("元素的转置",arr.T)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
数组的形状： (2, 2)
数组的维度 2
元素的个数 4
元素的类型： int64
元素的转置 [[1 3]
 [2 4]]


## 3、ndarry的创建

In [17]:
#基础的方法arr = np.array
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [19]:
list1=[1,2,3]
arr=np.array(list1,dtype=np.float64)
print(arr)
print(arr.ndim)

[1. 2. 3.]
1


In [22]:
#copy
arr1 = np.copy(arr)
print(arr1)
arr1[0]=8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [26]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
arr = np.zeros((2,1),dtype=np.int64)#两行一列
print(arr)
arr1 = np.zeros((3,),dtype=np.int64)#没有写列，默认是一列
print(arr1)

[[0]
 [0]]
[0 0 0]


In [27]:
#全1
arr = np.ones((2,1),dtype=np.int64)
print(arr)


[[1]
 [1]]


In [90]:
# 未初始化
arr = np.empty((9,2))
print(arr)

[[1.16773862e-311 4.84184333e-322]
 [0.00000000e+000 0.00000000e+000]
 [2.41907520e-312 1.16095484e-028]
 [2.95843127e+137 2.17229801e-153]
 [1.03301135e-113 1.75300433e+243]
 [1.67048256e-070 1.93499714e+131]
 [1.75300442e+243 1.67048256e-070]
 [6.32672800e+180 4.74483502e+170]
 [3.00948078e-067 8.70018433e-313]]


In [91]:
# 固定值
arr = np.full((3,4),2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [92]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [94]:
arr1 = np.full_like(arr,2026)
print(arr1)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [96]:
# 等差数列 1 2 3 4 5
arr = np.arange(1,10,3)#start end(not include) step
print(arr)

[1 4 7]


In [97]:
# 等间隔数列
app = np.linspace(1,10,5) #最后一个数表示均匀的分成几份，10也是包含在内的
print(app)

[ 1.    3.25  5.5   7.75 10.  ]


In [98]:
# 对数间隔数列
arr = np.logspace(0,10,25,base=2)
print(arr)

[1.00000000e+00 1.33483985e+00 1.78179744e+00 2.37841423e+00
 3.17480210e+00 4.23785238e+00 5.65685425e+00 7.55099450e+00
 1.00793684e+01 1.34543426e+01 1.79593928e+01 2.39729132e+01
 3.20000000e+01 4.27148753e+01 5.70175180e+01 7.61092554e+01
 1.01593667e+02 1.35611276e+02 1.81019336e+02 2.41631824e+02
 3.22539789e+02 4.30538965e+02 5.74700569e+02 7.67133223e+02
 1.02400000e+03]
