# ndarray
## 1、ndarray的特性
### 多维性

In [1]:
import numpy as np
from tinycss2 import parse_rule_list

In [3]:
arr = np.array(5) #创建0维的数组
print(arr)
print('arr的维度：',arr.ndim) # number of dimension

5
arr的维度： 0


In [2]:
arr = np.array([1])  #创建1维的数组
print(arr)
print('arr的维度：', arr.ndim)  # number of dimension

[1]
arr的维度： 1


In [3]:
arr = np.array([[1,2],[3,4]])  #创建2维的数组
print(arr)
print('arr的维度：', arr.ndim)  # number of dimension

[[1 2]
 [3 4]]
arr的维度： 2


### 同质性

## 2、ndarray的属性

In [14]:
arr = np.array(1)
print(arr)
print("数组的形状：",arr.shape)#按ctrl+k提交
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的类型：",arr.dtype)

1
数组的形状： ()
数组的维度 0
元素的个数 1
元素的类型： int64


In [15]:
arr = np.array([1,2.5])
print(arr)
print("数组的形状：",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的类型：",arr.dtype)

[1.  2.5]
数组的形状： (2,)
数组的维度 1
元素的个数 2
元素的类型： float64


In [16]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr)
print("数组的形状：",arr.shape)#两行两列
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的类型：",arr.dtype)
print("元素的转置",arr.T)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
数组的形状： (2, 2)
数组的维度 2
元素的个数 4
元素的类型： int64
元素的转置 [[1 3]
 [2 4]]


## 3、ndarry的创建

In [17]:
#基础的方法arr = np.array
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [19]:
list1=[1,2,3]
arr=np.array(list1,dtype=np.float64)
print(arr)
print(arr.ndim)

[1. 2. 3.]
1


In [22]:
#copy
arr1 = np.copy(arr)
print(arr1)
arr1[0]=8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [26]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
arr = np.zeros((2,1),dtype=np.int64)#两行一列
print(arr)
arr1 = np.zeros((3,),dtype=np.int64)#没有写列，默认是一列
print(arr1)

[[0]
 [0]]
[0 0 0]


In [27]:
#全1
arr = np.ones((2,1),dtype=np.int64)
print(arr)


[[1]
 [1]]


In [90]:
# 未初始化
arr = np.empty((9,2))
print(arr)

[[1.16773862e-311 4.84184333e-322]
 [0.00000000e+000 0.00000000e+000]
 [2.41907520e-312 1.16095484e-028]
 [2.95843127e+137 2.17229801e-153]
 [1.03301135e-113 1.75300433e+243]
 [1.67048256e-070 1.93499714e+131]
 [1.75300442e+243 1.67048256e-070]
 [6.32672800e+180 4.74483502e+170]
 [3.00948078e-067 8.70018433e-313]]


In [91]:
# 固定值
arr = np.full((3,4),2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [92]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [94]:
arr1 = np.full_like(arr,2026)
print(arr1)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [96]:
# 等差数列 1 2 3 4 5
arr = np.arange(1,10,3)#start end(not include) step
print(arr)

[1 4 7]


In [97]:
# 等间隔数列
app = np.linspace(1,10,5) #最后一个数表示均匀的分成几份，10也是包含在内的
print(app)

[ 1.    3.25  5.5   7.75 10.  ]


In [98]:
# 对数间隔数列
arr = np.logspace(0,10,25,base=2)
print(arr)

[1.00000000e+00 1.33483985e+00 1.78179744e+00 2.37841423e+00
 3.17480210e+00 4.23785238e+00 5.65685425e+00 7.55099450e+00
 1.00793684e+01 1.34543426e+01 1.79593928e+01 2.39729132e+01
 3.20000000e+01 4.27148753e+01 5.70175180e+01 7.61092554e+01
 1.01593667e+02 1.35611276e+02 1.81019336e+02 2.41631824e+02
 3.22539789e+02 4.30538965e+02 5.74700569e+02 7.67133223e+02
 1.02400000e+03]


In [3]:
# 特殊矩阵
# 单位矩阵，对称矩阵，转置矩阵
arr=np.eye(2,dtype=int)
print(arr)

[[1 0]
 [0 1]]


In [4]:
# 对角矩阵
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [7]:
# 随机数组的生成
# 生成0-1之间随机的浮点数
arr = np.random.rand(3,4)#生成三行四列的数据
print(arr)

[[0.06319804 0.71821713 0.40954703 0.25437962]
 [0.64745775 0.94067567 0.81199696 0.64626419]
 [0.54490573 0.92078125 0.37769113 0.10102097]]


In [8]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(low=-1,high=1,size=(3,4))
print(arr)

[[ 0.81355921  0.49259678  0.59458321 -0.53419477]
 [ 0.36153798  0.00311661 -0.68627886  0.90941438]
 [-0.57743019 -0.96821316  0.64282795  0.22008144]]


In [9]:
# 生成指定范围的随机证书
arr = np.random.randint(1,10,size=(3,4))
print(arr)

[[4 6 2 8]
 [7 4 2 8]
 [1 9 6 7]]


In [11]:
# 生成随机数列（正态分布）
arr = np.random.randn(2,3)
print(arr)

[[ 0.18443699  0.24455943 -0.81686994]
 [ 0.8536193  -0.48294465 -1.46410835]]


## 4、ndarray的数据类型
### bool,int,float,complex

In [12]:
arr = np.array([1,2],dtype='bool')
print(arr)

[ True  True]


## 5、索引与切片


In [11]:
# 一维数组的索引与切片
arr = np.random.randint(1,10,size=(3,4))
print(arr)
print(arr[0])
print(arr[1:2])#不包含2
print(arr[(arr<10) &(arr>6)])
print(arr[slice(0,2)])#不包含2

[[1 1 3 2]
 [9 9 4 5]
 [3 5 8 5]]
[1 1 3 2]
[[9 9 4 5]]
[9 9 8]
[[1 1 3 2]
 [9 9 4 5]]


# 6、ndarray的运算

In [12]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [13]:
c = np.array([1,2,3])
for i in range(len(c)):
    print(c[i])

1
2
3


In [14]:
a = np.array([1,2,3])
print(a+3)

[4 5 6]


In [16]:
# 广播机制，其中一个维度是1，另一个维度相同
a = np.array([1,2,3])#1*3
b = np.array([[1],[2],[3]]) #3*1
print(a+b)
'''纬度不同,进行扩展
a
1 2 3
1 2 3
1 2 3
b
1 1 1
2 2 2
3 3 3
'''

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [21]:
# 矩阵运算,需要形状相同或满足广播特性，形状相同的对应位置相乘
a = np.array([[1,2,3],[3,2,1]])
b = np.array([[2,2,2],[1,2,1]])
print(a*b)
c = np.array([[1,1,1],[1,2,1],[0,1,1]])
d = np.array([[1,1,1],[1,2,1],[0,1,1]])
print(c*d)
'''
a
1 2 3
3 2 1
b
2 2 2
1 1 1
'''

[[2 4 6]
 [3 4 1]]
[[1 1 1]
 [1 4 1]
 [0 1 1]]


'\na\n1 2 3\n3 2 1\nb\n2 2 2\n1 1 1\n'

## numpy的常用函数
### 1、基础数学函数

In [23]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))

3.0
[1. 2. 3.]


In [27]:
arr = np.array([1,4,9])
print(np.sqrt(arr))

[1. 2. 3.]


In [28]:
# 计算指数e^x
print(np.exp(1))

2.718281828459045


In [2]:
#计算自然对数
print(np.log(2))

0.6931471805599453


In [3]:
# 计算sinx
print(np.sin(2))

0.9092974268256817


In [4]:
# 计算绝对值
arr = np.array([-1,-2])
print(np.abs(arr))

[1 2]


In [5]:
# 计算a^b
print(np.power(arr,2))

[1 4]


In [6]:
# 四舍五入
print(np.round([1.2,1.6,2.3]))

[1. 2. 2.]


In [7]:
# 向上取整，向下取整
arr=np.array([1.6,1.2,25.1])
print(np.ceil(arr))
print(np.floor(arr))

[ 2.  2. 26.]
[ 1.  1. 25.]


### 2、统计函数
求和、计算、计算中位数、标准差、方差、查找最大值、查找最小值、计算分位数、累积和、累计差

In [13]:
arr = np.random.randint(1,10,8)
print(arr)
#求和
print(np.sum(arr))
#计算平均值
print((np.average(arr)))
#计算最大值
print(np.max(arr))
#计算最小值
print(np.min(arr))
#计算中位数,奇数：排序后中间数，偶数：排序后中间两个数的平均值
print(np.median(arr))
#计算标准差、方差
print(np.var(arr))
print(np.std(arr))

[5 7 4 3 9 5 8 8]
49
6.125
9
3
6.0
4.109375
2.027159342528357
